<?php

namespace AppBundle\Repository;

/**
 * HolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolderRepository extends \Doctrine\ORM\EntityRepository
{
}
